server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        #配置路由：路由id，路由到微服务的uri，断言(判断条件)
      - id: product-service  #保持唯一
        uri: http://localhost:9001 #目标微服务请求地址
        predicates:
        - Path=/product/** #路由条件： Path：路由匹配条件